//! Moderation audit-log domain model (T3.3).
//!
//! Append-only trail of every moderator action in a server. Written by the
//! Rust API only. The write form ([`NewModerationLogEntry`]) is built by the
//! service layer; the read form ([`ModerationLogEntry`]) carries actor/target
//! display data resolved at read time so the UI needs no extra fetch.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use super::ids::{ModerationLogId, ServerId, UserId};

/// A logged moderator action. Matches the Postgres `moderation_action` enum
/// (`snake_case` labels). Unknown DB values fail loudly (see [`Self::from_db_str`]).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ModerationAction {
    MemberKick,
    MemberBan,
    MemberUnban,
    MemberTimeout,
    MemberTimeoutRemove,
    MessageDelete,
    MessageBulkDelete,
}

impl ModerationAction {
    /// Postgres enum label. WHY hand-mapped (not the sqlx `Type` derive): the
    /// repository casts the enum column to/from `text` in SQL, mirroring
    /// `message_type` and `attachment_moderation_status` — no offline-metadata
    /// coupling to a custom SQL type.
    #[must_use]
    pub fn as_db_str(self) -> &'static str {
        match self {
            Self::MemberKick => "member_kick",
            Self::MemberBan => "member_ban",
            Self::MemberUnban => "member_unban",
            Self::MemberTimeout => "member_timeout",
            Self::MemberTimeoutRemove => "member_timeout_remove",
            Self::MessageDelete => "message_delete",
            Self::MessageBulkDelete => "message_bulk_delete",
        }
    }

    /// Parse a Postgres enum label. Returns `None` for an unrecognized value so
    /// the caller can surface a hard error rather than silently mislabel a row.
    #[must_use]
    pub fn from_db_str(s: &str) -> Option<Self> {
        match s {
            "member_kick" => Some(Self::MemberKick),
            "member_ban" => Some(Self::MemberBan),
            "member_unban" => Some(Self::MemberUnban),
            "member_timeout" => Some(Self::MemberTimeout),
            "member_timeout_remove" => Some(Self::MemberTimeoutRemove),
            "message_delete" => Some(Self::MessageDelete),
            "message_bulk_delete" => Some(Self::MessageBulkDelete),
            _ => None,
        }
    }
}

/// A moderation-log entry to persist (pre-insert form). The id and `created_at`
/// are generated by Postgres.
#[derive(Debug, Clone)]
pub struct NewModerationLogEntry {
    pub server_id: ServerId,
    pub action: ModerationAction,
    /// The moderator, or the system-moderator sentinel for automod deletes.
    pub actor_id: UserId,
    /// Target user for member actions. `None` for message-only actions.
    pub target_user_id: Option<UserId>,
    /// Target message for delete actions. `None` for member-only actions.
    pub target_message_id: Option<uuid::Uuid>,
    pub reason: Option<String>,
    /// Action-specific extras (`{"count":12}` etc). Always a JSON object.
    pub metadata: serde_json::Value,
}

impl NewModerationLogEntry {
    /// Convenience constructor with empty metadata — the common case for
    /// ban/kick/unban/delete where no extra fields are needed.
    #[must_use]
    pub fn new(
        server_id: ServerId,
        action: ModerationAction,
        actor_id: UserId,
        target_user_id: Option<UserId>,
        target_message_id: Option<uuid::Uuid>,
        reason: Option<String>,
    ) -> Self {
        Self {
            server_id,
            action,
            actor_id,
            target_user_id,
            target_message_id,
            reason,
            metadata: serde_json::json!({}),
        }
    }
}

/// A moderation-log entry as read back for the audit-log surface, with
/// actor/target display data resolved at read time.
#[derive(Debug, Clone)]
pub struct ModerationLogEntry {
    pub id: ModerationLogId,
    pub server_id: ServerId,
    pub action: ModerationAction,
    pub actor_id: UserId,
    /// Actor display name (username fallback). Empty if the actor profile was
    /// deleted (`actor_id` set NULL by the FK) — the UI renders "[unknown]".
    pub actor_username: String,
    pub actor_avatar_url: Option<String>,
    pub target_user_id: Option<UserId>,
    /// Target display name. `None` when there is no target user or the profile
    /// was deleted.
    pub target_username: Option<String>,
    pub target_message_id: Option<uuid::Uuid>,
    pub reason: Option<String>,
    pub metadata: serde_json::Value,
    pub created_at: DateTime<Utc>,
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::*;

    #[test]
    fn action_db_round_trip() {
        for action in [
            ModerationAction::MemberKick,
            ModerationAction::MemberBan,
            ModerationAction::MemberUnban,
            ModerationAction::MemberTimeout,
            ModerationAction::MemberTimeoutRemove,
            ModerationAction::MessageDelete,
            ModerationAction::MessageBulkDelete,
        ] {
            let s = action.as_db_str();
            assert_eq!(
                ModerationAction::from_db_str(s),
                Some(action),
                "round-trip failed for {s}"
            );
        }
    }

    #[test]
    fn action_db_str_is_snake_case() {
        assert_eq!(ModerationAction::MemberBan.as_db_str(), "member_ban");
        assert_eq!(
            ModerationAction::MessageBulkDelete.as_db_str(),
            "message_bulk_delete"
        );
    }

    #[test]
    fn action_from_unknown_is_none() {
        assert_eq!(ModerationAction::from_db_str("nope"), None);
        assert_eq!(ModerationAction::from_db_str(""), None);
    }

    #[test]
    fn action_json_matches_db_label() {
        // The JSON representation (serde snake_case) must equal the DB label so
        // the DTO layer and the enum column stay in lockstep.
        let json = serde_json::to_string(&ModerationAction::MemberTimeoutRemove).unwrap();
        assert_eq!(json, "\"member_timeout_remove\"");
    }
}
