//! Repository traits (ports) for hexagonal architecture.
//!
//! These traits define the contracts that infrastructure adapters must implement.

mod analytics_recorder;
mod attachment_repository;
mod attachment_scan_retry_repository;
mod ban_repository;
mod channel_repository;
mod content_moderator;
mod csam_matcher;
mod desktop_auth_repository;
pub mod dm_repository;
mod emoji_image_scan_retry_repository;
mod event_bus;
pub mod friendship_repository;
mod identity_image_scan_retry_repository;
mod image_classifier;
mod invite_repository;
mod key_repository;
mod livekit;
mod megolm_session_repository;
mod member_repository;
mod message_repository;
mod migration_dashboard_repository;
mod moderation_log_repository;
mod moderation_retry_repository;
mod notification_settings_repository;
mod plan_limit_checker;
mod profile_repository;
mod reaction_repository;
mod read_state_repository;
mod report_repository;
mod server_emoji_repository;
mod server_repository;
mod storage_object_remover;
mod user_preferences_repository;
mod voice_session_repository;

pub use analytics_recorder::AnalyticsRecorder;
pub use attachment_repository::AttachmentRepository;
pub use attachment_scan_retry_repository::AttachmentScanRetryRepository;
pub use ban_repository::BanRepository;
pub use channel_repository::ChannelRepository;
pub use content_moderator::{ContentModerator, ModerationResult};
pub use csam_matcher::{CsamMatcher, CsamVerdict};
pub use desktop_auth_repository::DesktopAuthRepository;
pub use dm_repository::DmRepository;
pub use emoji_image_scan_retry_repository::EmojiImageScanRetryRepository;
pub use event_bus::EventBus;
pub use friendship_repository::FriendshipRepository;
pub use identity_image_scan_retry_repository::IdentityImageScanRetryRepository;
pub use image_classifier::{ImageClassifier, NsfwLabel, NsfwVerdict};
pub use invite_repository::InviteRepository;
pub use key_repository::KeyRepository;
pub use livekit::{LiveKitTokenGenerator, VoiceGrants};
pub use megolm_session_repository::MegolmSessionRepository;
pub use member_repository::MemberRepository;
pub use message_repository::{AroundWindow, MessageRepository, MessageSearchFilters};
pub use migration_dashboard_repository::MigrationDashboardRepository;
pub use moderation_log_repository::ModerationLogRepository;
pub use moderation_retry_repository::ModerationRetryRepository;
pub use notification_settings_repository::{NotificationLevel, NotificationSettingsRepository};
pub use plan_limit_checker::PlanLimitChecker;
pub use profile_repository::ProfileRepository;
pub use reaction_repository::ReactionRepository;
pub use read_state_repository::ReadStateRepository;
pub use report_repository::ReportRepository;
pub use server_emoji_repository::ServerEmojiRepository;
pub use server_repository::ServerRepository;
pub use storage_object_remover::StorageObjectRemover;
pub use user_preferences_repository::{UpdatePreferences, UserPreferencesRepository};
pub use voice_session_repository::VoiceSessionRepository;
